// import bcrypt from 'bcryptjs';

// Object with data arrays for users & products
const DATA = {
	products: [
		{
			name: 'Free Shirt International Choice',
			slug: 'free-shirt',
			category: 'Shirts',
			image: '/images/shirt1.jpg',
			isFeatured: true,
			featuredImage: '/images/banner1.jpg',
			price: 90,
			brand: 'Nike',
			rating: 4.5,
			numReviews: 10,
			countInStock: 20,
			description: 'A popular shirt',
		},
		{
			name: 'Chrome Shirt American Customier',
			slug: 'fit-shirt',
			category: 'Shirts',
			image: '/images/shirt2.jpg',
			isFeatured: true,
			featuredImage: '/images/banner2.jpg',
			price: 80,
			brand: 'Adidas',
			rating: 4.2,
			numReviews: 10,
			countInStock: 20,
			description: 'A popular shirt',
		},
		{
			name: 'Slim Shirt Summer Continental',
			slug: 'slim-shirt',
			category: 'Shirts',
			image: '/images/shirt3.jpg',
			price: 90,
			brand: 'Raymond',
			rating: 4.5,
			numReviews: 10,
			countInStock: 20,
			description: 'A popular shirt',
		},
		{
			name: 'Golf Pants Wealthy Sportmanship',
			slug: 'golf-pants',
			category: 'Pants',
			image: '/images/pants1.jpg',
			price: 90,
			brand: 'Oliver',
			rating: 4.5,
			numReviews: 10,
			countInStock: 20,
			description: 'Smart looking pants',
		},
		{
			name: 'Classic Pants Professional Golfer',
			slug: 'classic-pants',
			category: 'Pants',
			image: '/images/pants3.jpg',
			price: 75,
			brand: 'Casely',
			rating: 4.5,
			numReviews: 10,
			countInStock: 20,
			description: 'A popular pants',
		},
		{
			name: 'Fit Pants Negro Exotic Arkansas',
			slug: 'fit-pants',
			category: 'Pants',
			image: '/images/pants2.jpg',
			price: 95,
			brand: 'Zara',
			rating: 4.5,
			numReviews: 10,
			countInStock: 20,
			description: 'A popular pants',
		},
	],
};

export default DATA;
