import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

//
export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Emzor Boutique</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link
					rel='icon'
					href='/favicon.ico'
				/>
			</Head>

			{/* main section */}
			<main className={styles.main}>
				<div>
					<h1>Welcome here...</h1>
					<ul>
						<li>Product 1</li>
						<li>Product 2</li>
						<li>Product 3</li>
					</ul>
				</div>
			</main>

			{/* footer section */}
			<footer className={styles.footer}>
				<a href=''>
					Powered by
					<span className={styles.logo}>
						<Image
							src='/vercel.svg'
							alt='logo'
							width={72}
							height={16}
						/>
					</span>
				</a>
			</footer>
		</div>
	);
}
